"""Report-generation service for HTML, JSON, and PDF artifacts."""
from __future__ import annotations

import json
import html
import re
from collections import Counter
from pathlib import Path
from typing import Callable, Iterable

try:
    from pydantic import BaseModel, Field
except ImportError:
    class BaseModel:
        def __init__(self, **kwargs):
            for key, value in kwargs.items():
                setattr(self, key, value)

    def Field(default=None, **kwargs):  # type: ignore
        if "default_factory" in kwargs:
            return kwargs["default_factory"]()
        return default

from packages.citation_sources.models import CitingPaper, FetchSummary, SourceTrace
from packages.reporting.country_resolution import AuthorCountryInput, CountryResolution, CountryResolverProtocol, HybridCountryResolver
from packages.reporting.map_data import build_country_map_payload, load_world_geojson
from packages.reporting.pdf_renderer import render_pdf_report
from packages.reporting.title_translation import translate_title_to_chinese
from packages.sentiment.models import CitationContext, SentimentSummary
from packages.shared.models import AnalysisState, AuthorProfile, AuthorSummary, ReportArtifact, ScholarLabel, TargetPaper
from packages.shared.runtime_logging import get_runtime_logger


DEFAULT_REPORT_DIR = Path("generated-reports")
SENTIMENT_LABEL_DISPLAY = {
    "positive": "正向",
    "neutral": "中性",
    "critical": "批评",
    "unknown": "未知",
}
SCHOLAR_LABEL_DISPLAY = {
    "heavyweight_candidate": "重量级候选",
    "high_impact_candidate": "高影响力候选",
    "weak_signal_candidate": "普通学者",
}
SENTIMENT_ORDER = ["critical", "neutral", "positive", "unknown"]
SENTIMENT_COLORS = {
    "critical": "#b85c42",
    "neutral": "#8f8172",
    "positive": "#6f8f5b",
    "unknown": "#b9aa96",
}
ECHARTS_CDN_URL = "https://cdn.jsdelivr.net/npm/echarts@6.0.0/dist/echarts.min.js"
INSTITUTION_TOP_N = 8
H_INDEX_BUCKETS = (
    ("0-9", 0, 9),
    ("10-19", 10, 19),
    ("20-29", 20, 29),
    ("30-49", 30, 49),
    ("50-99", 50, 99),
    ("100+", 100, None),
)
ExecutiveSummaryBuilder = Callable[[dict[str, object]], list[str]]


class ExecutiveSummaryModel(BaseModel):
    """Validate reader-facing Chinese summary bullets generated by the LLM."""
    bullets: list[str] = Field(
        default_factory=list,
        description="4 到 5 条中文分析摘要，每条是一句完整、面向读者的话。",
    )


def build_report_artifact(
    target_paper: TargetPaper,
    citing_papers: list[CitingPaper],
    author_profiles: list[AuthorProfile],
    scholar_labels: list[ScholarLabel],
    author_summary: AuthorSummary,
    citation_contexts: list[CitationContext],
    sentiment_summary: SentimentSummary,
    fetch_summary: FetchSummary | None = None,
    source_trace: list[SourceTrace] | None = None,
    state_errors: list[str] | None = None,
    author_identity_skipped_papers: list[dict[str, str]] | None = None,
    output_dir: Path | None = None,
    country_resolver: CountryResolverProtocol | None = None,
    title_translator: Callable[[str], str | None] | None = translate_title_to_chinese,
    executive_summary_builder: ExecutiveSummaryBuilder | None = None,
) -> ReportArtifact:
    """Build report files from citation, author, sentiment, and provenance data."""
    report_id = target_paper.canonical_id or target_paper.doi or target_paper.title or "unknown-target"
    safe_report_id = _slugify(report_id)
    report_dir = (output_dir or DEFAULT_REPORT_DIR).resolve() / safe_report_id
    report_dir.mkdir(parents=True, exist_ok=True)

    provenance = _build_provenance(
        fetch_summary,
        source_trace,
        state_errors,
        scholar_labels,
        author_profiles,
        author_identity_skipped_papers,
    )
    institution_distribution = _build_institution_distribution(author_profiles)
    country_distribution, country_trace = _build_country_distribution(author_profiles, country_resolver)
    provenance["country_resolution_trace"] = country_trace
    provenance["report_warnings"] = []
    provenance["pdf_export_status"] = "pending"
    target_title_zh = _translate_target_title(target_paper.title, title_translator, provenance)
    target_arxiv_id = _target_arxiv_id(target_paper)
    target_arxiv_url = f"https://arxiv.org/abs/{target_arxiv_id}" if target_arxiv_id else None
    chart_payloads = {
        "year_trend": _build_year_trend(citing_papers),
        "institution_distribution": institution_distribution,
        "source_map": institution_distribution,
        "country_distribution": country_distribution,
        "scholar_distribution": _build_scholar_distribution(scholar_labels),
        "h_index_distribution": _build_h_index_distribution(author_profiles),
        "sentiment_distribution": dict(sentiment_summary.label_counts),
    }
    summary = {
        "target_title": target_paper.title,
        "target_title_zh": target_title_zh,
        "target_doi": target_paper.doi,
        "target_arxiv_id": target_arxiv_id,
        "target_arxiv_url": target_arxiv_url,
        "citation_count": len(citing_papers),
        "heavyweight_candidates": author_summary.heavyweight_candidates,
        "high_impact_candidates": author_summary.high_impact_candidates,
        "weak_signal_candidates": author_summary.weak_signal_candidates,
        "author_profile_breakdown": provenance["author_profile_breakdown"],
        "context_found": sentiment_summary.context_found,
        "unknown_sentiments": sentiment_summary.unknown_count,
        "partial_failure": provenance["partial_failure"],
        "source_trace_count": provenance["source_trace_count"],
        "source_trace_sources": provenance["source_trace_sources"],
        "executive_summary": _build_executive_summary(
            citing_papers,
            scholar_labels,
            sentiment_summary,
            chart_payloads,
            provenance,
            summary_builder=executive_summary_builder,
        ),
        "key_findings": _build_key_findings(citing_papers, scholar_labels, sentiment_summary, provenance),
        "top_scholars": _build_top_scholars(author_profiles, scholar_labels),
        "representative_contexts": _build_representative_contexts(citation_contexts, citing_papers),
        "manual_attention_items": _build_manual_attention_items(citation_contexts, scholar_labels, provenance),
        "author_identity_skipped_papers": list(author_identity_skipped_papers or []),
        "pdf_export_status": "pending",
    }

    json_path = report_dir / "report.json"
    html_path = report_dir / "report.html"
    pdf_path = report_dir / "report.pdf"
    payload = {
        "summary": summary,
        "charts": chart_payloads,
        "provenance": provenance,
        "contexts": [_serialize_context(context) for context in citation_contexts],
    }

    export_paths = {
        "html": str(html_path),
        "json": str(json_path),
    }
    try:
        render_pdf_report(payload, pdf_path)
    except Exception as exc:  # PDF export is not allowed to break HTML/JSON.
        reason = f"pdf_export_unavailable:{exc.__class__.__name__}:{exc}"
        provenance["pdf_export_status"] = "unavailable"
        provenance["report_warnings"].append(reason)  # type: ignore[union-attr]
        summary["pdf_export_status"] = "unavailable"
        get_runtime_logger().warn("report.pdf", "PDF 导出不可用，HTML/JSON 已生成", reason=reason)
    else:
        provenance["pdf_export_status"] = "generated"
        summary["pdf_export_status"] = "generated"
        export_paths["pdf"] = str(pdf_path)

    json_path.write_text(
        json.dumps(
            payload,
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    html_path.write_text(
        _render_html(target_paper, summary, chart_payloads, provenance, citation_contexts),
        encoding="utf-8",
    )

    return ReportArtifact(
        report_id=safe_report_id,
        target_paper_id=target_paper.canonical_id or target_paper.doi or safe_report_id,
        summary=summary,
        charts=chart_payloads,
        export_paths=export_paths,
    )


def attach_report_artifact_to_state(state: AnalysisState, artifact: ReportArtifact) -> AnalysisState:
    """Store generated report paths and mark the analyzer state as report-ready."""
    state["report_artifact"] = artifact  # type: ignore[assignment]
    state["status"] = "report_generated"
    return state


def _build_year_trend(citing_papers: Iterable[CitingPaper]) -> dict[str, int]:
    """Count citing papers per publication year for trend visualization."""
    counts = Counter(str(paper.year) for paper in citing_papers if paper.year is not None)
    return dict(sorted(counts.items()))


def _build_institution_distribution(author_profiles: Iterable[AuthorProfile]) -> dict[str, int]:
    """Count first-known author affiliations for institution distribution charts."""
    counts = Counter()
    for profile in author_profiles:
        if profile.affiliations:
            counts[profile.affiliations[0]] += 1
    return dict(sorted(counts.items()))


def _build_country_distribution(
    author_profiles: Iterable[AuthorProfile],
    resolver: CountryResolverProtocol | None = None,
) -> tuple[dict[str, int], list[dict[str, object]]]:
    """Resolve author country buckets from explicit country hints, institutions, and LLM inference."""
    active_resolver = resolver or HybridCountryResolver()
    profiles = list(author_profiles)
    author_inputs = [
        AuthorCountryInput(
            author_id=profile.source_ids.get("openalex") or profile.author_id,
            author_name=profile.name,
            institutions=tuple(institution for institution in profile.affiliations if institution.strip()),
            country_hints=tuple(country for country in profile.countries if country.strip()),
        )
        for profile in profiles
    ]
    if hasattr(active_resolver, "resolve_author_many"):
        resolved_by_author = active_resolver.resolve_author_many(author_inputs)  # type: ignore[attr-defined]
    else:
        resolved_by_author = {}
        institutions = [
            profile.affiliations[0]
            for profile in profiles
            if profile.affiliations and profile.affiliations[0].strip()
        ]
        resolved_by_institution = active_resolver.resolve_many(list(dict.fromkeys(institutions))) if hasattr(active_resolver, "resolve_many") else {}  # type: ignore[attr-defined]
    counts = Counter()
    trace = []
    for profile, author_input in zip(profiles, author_inputs):
        result = resolved_by_author.get(author_input.author_id)
        if result is None and "resolved_by_institution" in locals():
            institution = profile.affiliations[0] if profile.affiliations else ""
            result = resolved_by_institution.get(institution) if institution else None
            if result is None and institution:
                result = active_resolver.resolve(institution)
                resolved_by_institution[institution] = result
        if result is None:
            counts["Unknown"] += 1
            trace.append(
                {
                    "author_id": author_input.author_id,
                    "author_name": author_input.author_name,
                    "institution": "",
                    "country": "Unknown",
                    "country_code": None,
                    "confidence": "low",
                    "method": "missing",
                    "evidence": f"{profile.name}: 缺少明确国家代码、国家名和机构字段。",
                    "needs_review": True,
                    "basis": "unknown",
                    "is_inferred": False,
                    "country_hints": list(author_input.country_hints),
                }
            )
            continue
        counts[result.country] += 1
        trace.append(result.to_dict())
    return dict(sorted(counts.items())), trace


def _translate_target_title(
    title: str | None,
    title_translator: Callable[[str], str | None] | None,
    provenance: dict[str, object],
) -> str | None:
    """Translate the target title without letting LLM failures break reports."""
    if not title or not title_translator:
        return None
    try:
        return title_translator(title)
    except Exception as exc:
        reason = f"title_translation_unavailable:{exc.__class__.__name__}:{exc}"
        report_warnings = provenance.setdefault("report_warnings", [])
        if isinstance(report_warnings, list):
            report_warnings.append(reason)
        get_runtime_logger().warn("report.title_translation", "中文标题翻译不可用，报告继续生成", reason=reason)
        return None


def _target_arxiv_id(target_paper: TargetPaper) -> str | None:
    """Return the normalized arXiv identifier when the target paper has one."""
    candidates = [
        target_paper.source_ids.get("arxiv") if target_paper.source_ids else None,
        target_paper.source_ids.get("arxiv_id") if target_paper.source_ids else None,
        target_paper.paper_query if target_paper.paper_query_type == "arxiv" else None,
        target_paper.canonical_id,
    ]
    for candidate in candidates:
        if not candidate:
            continue
        match = re.search(r"(?P<id>\d{4}\.\d{4,5}(?:v\d+)?)", str(candidate), re.IGNORECASE)
        if match:
            return match.group("id")
    return None


def _build_scholar_distribution(labels: Iterable[ScholarLabel]) -> dict[str, int]:
    """Count scholar labels for the author-impact overview chart."""
    counts = Counter(label.label for label in labels)
    return dict(sorted(counts.items()))


def _build_h_index_distribution(author_profiles: Iterable[AuthorProfile]) -> dict[str, int]:
    """Bucket authors by h-index for a reader-facing distribution chart."""
    counts = Counter({label: 0 for label, _, _ in H_INDEX_BUCKETS})
    for profile in author_profiles:
        if profile.h_index is None:
            continue
        h_index = int(profile.h_index)
        for label, lower, upper in H_INDEX_BUCKETS:
            if h_index >= lower and (upper is None or h_index <= upper):
                counts[label] += 1
                break
    return dict(counts)


def _build_author_profile_breakdown(
    author_profiles: Iterable[AuthorProfile],
    scholar_labels: Iterable[ScholarLabel],
) -> dict[str, int]:
    """Classify author profiles by evidence completeness and impact rules."""
    labels_by_author = {label.author_id: label for label in scholar_labels}
    counts = Counter(
        {
            "heavyweight": 0,
            "high_impact": 0,
            "complete_regular": 0,
            "complete_missing_metric": 0,
            "weak_work_authorship": 0,
            "profile_total": 0,
            "complete_profile_total": 0,
        }
    )
    for profile in author_profiles:
        counts["profile_total"] += 1
        label = labels_by_author.get(profile.author_id)
        has_complete_profile = "openalex_author_id" in set(profile.evidence_sources)
        if has_complete_profile:
            counts["complete_profile_total"] += 1
        if label and label.label == "heavyweight_candidate":
            counts["heavyweight"] += 1
        elif label and label.label == "high_impact_candidate":
            counts["high_impact"] += 1
        elif has_complete_profile and profile.h_index is not None:
            counts["complete_regular"] += 1
        elif has_complete_profile:
            counts["complete_missing_metric"] += 1
        else:
            counts["weak_work_authorship"] += 1
    return dict(counts)


def _build_key_findings(
    citing_papers: list[CitingPaper],
    scholar_labels: list[ScholarLabel],
    sentiment_summary: SentimentSummary,
    provenance: dict[str, object],
) -> list[str]:
    """Create short findings that summarize citation volume, authors, and sentiment."""
    findings = [
        f"共识别 {len(citing_papers)} 篇施引论文。",
        f"重量级学者候选 {sum(1 for label in scholar_labels if label.label == 'heavyweight_candidate')} 位。",
        f"已分类引用 {sentiment_summary.classified_count} 条，无法判断 {sentiment_summary.unknown_count} 条。",
    ]
    if provenance["partial_failure"]:
        findings.append("上游抓取或解析存在部分失败，结论需结合注意事项复核。")
    breakdown = provenance.get("author_profile_breakdown")
    if isinstance(breakdown, dict):
        findings.append(
            "作者画像分类："
            f"完整画像 {breakdown.get('complete_profile_total', 0)} 位，"
            f"弱画像 {breakdown.get('weak_work_authorship', 0)} 位。"
        )
    skipped_authors = provenance.get("author_identity_skipped_papers")
    if isinstance(skipped_authors, list) and skipped_authors:
        findings.append(f"作者画像跳过 {len(skipped_authors)} 篇施引论文，以避免低置信作者错配。")
    return findings


def _build_executive_summary(
    citing_papers: list[CitingPaper],
    scholar_labels: list[ScholarLabel],
    sentiment_summary: SentimentSummary,
    charts: dict[str, object],
    provenance: dict[str, object],
    *,
    summary_builder: ExecutiveSummaryBuilder | None = None,
) -> list[str]:
    """Create reader-facing summary bullets with LLM wording and safe fallback."""
    facts = _build_executive_summary_facts(citing_papers, scholar_labels, sentiment_summary, charts, provenance)
    if summary_builder is not None:
        try:
            bullets = _sanitize_executive_summary_bullets(summary_builder(facts))
        except Exception as exc:
            _append_report_warning(provenance, f"executive_summary_builder_failed:{exc.__class__.__name__}:{exc}")
        else:
            if bullets:
                provenance["executive_summary_source"] = "custom_builder"
                return bullets

    try:
        bullets = _build_llm_executive_summary(facts)
    except Exception as exc:
        _append_report_warning(provenance, f"executive_summary_llm_failed:{exc.__class__.__name__}:{exc}")
    else:
        bullets = _sanitize_executive_summary_bullets(bullets)
        if bullets:
            provenance["executive_summary_source"] = "llm"
            return bullets

    provenance["executive_summary_source"] = "fallback"
    return _build_fallback_executive_summary(facts)


def _build_executive_summary_facts(
    citing_papers: list[CitingPaper],
    scholar_labels: list[ScholarLabel],
    sentiment_summary: SentimentSummary,
    charts: dict[str, object],
    provenance: dict[str, object],
) -> dict[str, object]:
    """Collect the exact numeric facts allowed in the executive summary prompt."""
    year_trend = _coerce_int_map(charts.get("year_trend"))
    country_distribution = _coerce_int_map(charts.get("country_distribution"))
    author_profile_breakdown = provenance.get("author_profile_breakdown")
    author_profile_breakdown = author_profile_breakdown if isinstance(author_profile_breakdown, dict) else {}
    total_authors = _as_int(author_profile_breakdown.get("profile_total"))
    unknown_country_count = country_distribution.get("Unknown", 0)
    located_country_count = max(total_authors - unknown_country_count, 0) if total_authors else 0
    heavyweight_count = sum(1 for label in scholar_labels if label.label == "heavyweight_candidate")
    high_impact_count = sum(1 for label in scholar_labels if label.label == "high_impact_candidate")
    important_scholars = sum(
        1
        for label in scholar_labels
        if label.label in {"heavyweight_candidate", "high_impact_candidate"}
    )
    peak_year = None
    peak_count = None
    if year_trend:
        peak_year, peak_count = max(year_trend.items(), key=lambda item: item[1])

    return {
        "citation_count": len(citing_papers),
        "classified_sentiments": sentiment_summary.classified_count,
        "unknown_sentiments": sentiment_summary.unknown_count,
        "sentiment_counts": dict(sentiment_summary.label_counts),
        "heavyweight_candidates": heavyweight_count,
        "high_impact_candidates": high_impact_count,
        "important_scholar_candidates": important_scholars,
        "peak_year": peak_year,
        "peak_count": peak_count,
        "dedup_author_count": total_authors,
        "country_located_count": located_country_count,
        "country_unknown_count": unknown_country_count,
        "complete_author_profiles": _as_int(author_profile_breakdown.get("complete_profile_total")),
        "skipped_author_papers": len(provenance.get("author_identity_skipped_papers", []))
        if isinstance(provenance.get("author_identity_skipped_papers"), list)
        else 0,
        "partial_failure": bool(provenance.get("partial_failure")),
        "state_error_count": len(provenance.get("state_errors", []))
        if isinstance(provenance.get("state_errors"), list)
        else 0,
        "fetch_note_count": len(provenance.get("fetch_notes", []))
        if isinstance(provenance.get("fetch_notes"), list)
        else 0,
    }


def _build_llm_executive_summary(facts: dict[str, object]) -> list[str]:
    """Ask the configured LLM to write concise Chinese report-summary bullets."""
    from apps.analyzer.config import build_llm, invoke_llm_with_retry

    structured_llm = build_llm().with_structured_output(ExecutiveSummaryModel, method="function_calling")
    prompt = (
        "你正在为中文论文被引分析报告撰写“分析摘要”。"
        "只能使用用户提供的事实和数字，不能新增、猜测或夸大结论。"
        "输出 4 到 5 条 bullets，每条必须是一句完整、自然、面向读者的中文。"
        "必须把字段转写成自然语言：citation_count 写成“施引文献数量”，dedup_author_count 写成“去重施引作者数”。"
        "绝对不要在摘要中出现 citation_count、dedup_author_count、unknown_sentiments、classified_sentiments 等英文变量名。"
        "未知情感的原因应概括为“全文不可用、引用上下文未命中或证据不足”。"
        "必须说明重要学者候选是系统按 h-index 与施引频次规则筛选，不是人工确认。"
        "必须使用“重量级候选”这个术语，不要改写成“重磅学者候选”。"
        "国家/地区部分必须写成“已定位 X/Y 位作者，另有 Z 位缺少可定位国家信息”。"
        "不要写“Unknown 当前最多”，不要把 Unknown 当作国家/地区，不要出现 Data Quality、人工关注项、debug 等工程术语。"
        "不要使用 Markdown 加粗、编号或多余标题。"
    )
    result = invoke_llm_with_retry(
        structured_llm,
        [
            {"role": "system", "content": prompt},
            {"role": "user", "content": json.dumps(facts, ensure_ascii=False, indent=2)},
        ],
        "阶段7分析摘要生成",
    )
    return list(getattr(result, "bullets", []) or [])


def _build_fallback_executive_summary(facts: dict[str, object]) -> list[str]:
    """Generate stable Chinese summary bullets when LLM wording is unavailable."""
    citation_count = _as_int(facts.get("citation_count"))
    classified = _as_int(facts.get("classified_sentiments"))
    unknown = _as_int(facts.get("unknown_sentiments"))
    important = _as_int(facts.get("important_scholar_candidates"))
    heavyweight = _as_int(facts.get("heavyweight_candidates"))
    high_impact = _as_int(facts.get("high_impact_candidates"))
    total_authors = _as_int(facts.get("dedup_author_count"))
    located = _as_int(facts.get("country_located_count"))
    country_unknown = _as_int(facts.get("country_unknown_count"))
    summary = [
        f"本次共识别 {citation_count} 篇施引文献，形成当前可复核的数据快照。",
        f"在 {citation_count} 篇施引文献中，{classified} 篇已完成引用情感判断，{unknown} 篇因全文不可用、引用上下文未命中或证据不足暂未判断。",
        f"系统按 h-index 与施引频次筛出 {important} 位重要学者候选，其中重量级候选 {heavyweight} 位、高影响力候选 {high_impact} 位。",
    ]
    peak_year = facts.get("peak_year")
    peak_count = facts.get("peak_count")
    if peak_year and peak_count is not None:
        summary.append(f"施引年份峰值出现在 {peak_year} 年，共 {peak_count} 篇。")
    if total_authors:
        summary.append(f"本次共识别 {total_authors} 位去重施引作者，其中 {located} 位可定位国家/地区，另有 {country_unknown} 位缺少可定位国家信息。")
    return summary[:5]


def _sanitize_executive_summary_bullets(bullets: list[str]) -> list[str]:
    """Keep generated summary bullets concise and remove unsafe reader-facing phrasing."""
    cleaned: list[str] = []
    banned_fragments = (
        "Unknown 当前最多",
        "Data Quality",
        "人工关注项",
        "debug",
        "Debug",
        "citation_count",
        "dedup_author_count",
        "unknown_sentiments",
        "classified_sentiments",
        "重磅学者",
    )
    for bullet in bullets:
        text = re.sub(r"\s+", " ", str(bullet or "")).strip(" -•\t\r\n")
        if not text or any(fragment in text for fragment in banned_fragments):
            continue
        cleaned.append(text)
        if len(cleaned) >= 5:
            break
    return cleaned if len(cleaned) >= 4 else []


def _append_report_warning(provenance: dict[str, object], warning: str) -> None:
    """Append a report-generation warning while preserving existing provenance shape."""
    warnings = provenance.setdefault("report_warnings", [])
    if isinstance(warnings, list):
        warnings.append(warning)


def _build_top_scholars(author_profiles: list[AuthorProfile], scholar_labels: list[ScholarLabel], limit: int = 10) -> list[dict[str, object]]:
    """Select scholar candidates with metrics and label evidence for tables."""
    labels_by_author = {label.author_id: label for label in scholar_labels}
    ranked_profiles = sorted(
        author_profiles,
        key=lambda profile: (
            0 if labels_by_author.get(profile.author_id, None) and labels_by_author[profile.author_id].label == "heavyweight_candidate" else
            1 if labels_by_author.get(profile.author_id, None) and labels_by_author[profile.author_id].label == "high_impact_candidate" else
            2,
            -(profile.h_index or 0),
            profile.name,
        ),
    )
    result = []
    for profile in ranked_profiles[:limit]:
        label = labels_by_author.get(profile.author_id)
        result.append(
            {
                "author_id": profile.author_id,
                "name": profile.name,
                "label": _display_scholar_label(label.label) if label else "未标注",
                "raw_label": label.label if label else None,
                "h_index": profile.h_index,
                "citation_count": profile.citation_count,
                "works_count": profile.works_count,
                "affiliations": list(profile.affiliations),
                "fields": list(profile.fields),
                "evidence": list(label.evidence) if label else list(profile.evidence_sources),
            }
        )
    return result


def _build_representative_contexts(
    citation_contexts: list[CitationContext],
    citing_papers: list[CitingPaper],
    limit_per_label: int = 3,
) -> dict[str, list[dict[str, object]]]:
    """Group representative citation contexts by sentiment for report sections."""
    grouped: dict[str, list[dict[str, object]]] = {"positive": [], "critical": [], "neutral": []}
    paper_by_id = {paper.canonical_id: paper for paper in citing_papers}
    context_counts: Counter[str] = Counter()
    for context in citation_contexts:
        if context.sentiment_label not in grouped or not context.context_text:
            continue
        if len(grouped[context.sentiment_label]) >= limit_per_label:
            continue
        context_counts[context.citing_paper_id] += 1
        grouped[context.sentiment_label].append(
            _serialize_context(
                context,
                citing_paper=paper_by_id.get(context.citing_paper_id),
                context_index=context_counts[context.citing_paper_id],
            )
        )
    return grouped


def _build_manual_attention_items(
    citation_contexts: Iterable[CitationContext],
    scholar_labels: Iterable[ScholarLabel],
    provenance: dict[str, object],
) -> list[str]:
    """List data-quality issues that should be reviewed alongside report claims."""
    items = []
    for context in citation_contexts:
        if context.sentiment_label == "unknown":
            items.append(f"{context.citing_paper_id}: {context.evidence_note}")
    if provenance["partial_failure"]:
        fetch_notes = provenance["fetch_notes"] or ["partial_fetch_failure"]
        items.extend(f"fetch: {note}" for note in fetch_notes)
    items.extend(str(error) for error in provenance["state_errors"])
    for item in provenance.get("author_identity_skipped_papers", []):
        if isinstance(item, dict):
            items.append(f"author_identity_skip:{item.get('citing_paper_id')}: {item.get('reason')}")
    for label in scholar_labels:
        if label.confidence_note:
            items.append(f"{label.author_id}: {label.label}: {label.confidence_note}")
    return items


def _build_provenance(
    fetch_summary: FetchSummary | None,
    source_trace: list[SourceTrace] | None,
    state_errors: list[str] | None,
    scholar_labels: list[ScholarLabel],
    author_profiles: list[AuthorProfile],
    author_identity_skipped_papers: list[dict[str, str]] | None = None,
) -> dict[str, object]:
    """Assemble source, failure, and country-resolution traces for auditability."""
    trace = source_trace or []
    author_profile_breakdown = _build_author_profile_breakdown(author_profiles, scholar_labels)
    return {
        "partial_failure": bool(fetch_summary.partial_failure) if fetch_summary else False,
        "fetch_notes": list(fetch_summary.notes) if fetch_summary else [],
        "source_trace_count": len(trace),
        "source_trace_sources": sorted({item.source_name for item in trace if item.source_name}),
        "state_errors": list(state_errors or []),
        "author_identity_skipped_papers": list(author_identity_skipped_papers or []),
        "author_profile_breakdown": author_profile_breakdown,
        "low_confidence_labels": [
            {
                "author_id": label.author_id,
                "label": label.label,
                "confidence_note": label.confidence_note,
                "evidence": list(label.evidence),
            }
            for label in scholar_labels
            if label.confidence_note
        ],
    }


def _serialize_context(
    context: CitationContext,
    citing_paper: CitingPaper | None = None,
    context_index: int | None = None,
) -> dict[str, object]:
    return {
        "citing_paper_id": context.citing_paper_id,
        "citing_paper_title": citing_paper.title if citing_paper else None,
        "citing_paper_doi": citing_paper.doi if citing_paper else None,
        "citing_paper_year": citing_paper.year if citing_paper else None,
        "context_index": context_index,
        "sentiment_label": context.sentiment_label,
        "context_text": context.context_text,
        "matched_target_reference": context.matched_target_reference,
        "evidence_note": context.evidence_note,
        "reason": _display_reason(context.evidence_note),
        "text_source_type": context.text_source_type,
        "text_source_label": context.text_source_label,
    }


def _display_sentiment_label(label: str) -> str:
    return SENTIMENT_LABEL_DISPLAY.get(label, label)


def _display_scholar_label(label: str) -> str:
    return SCHOLAR_LABEL_DISPLAY.get(label, label)


def _display_reason(evidence_note: str | None) -> str:
    """Extract a human-readable report reason from raw pipeline evidence."""
    if not evidence_note:
        return "上下文证据不足，无法形成可靠判断。"
    reason = str(evidence_note).strip()
    if "llm_sentiment:" in reason:
        reason = reason.split("llm_sentiment:")[-1].strip()
    else:
        parts = [part.strip() for part in reason.split(";") if part.strip()]
        readable_parts = [
            part
            for part in parts
            if not re.match(r"^(matched_by_|no_text_available|context_too_short|grobid_|reference_)", part)
        ]
        reason = readable_parts[-1] if readable_parts else reason
    reason = re.sub(r"^(原因[:：]\s*)+", "", reason).strip()
    if not reason:
        return "上下文证据不足，无法形成可靠判断。"
    return reason


def _escape_html(value: object) -> str:
    """Escape report display values before placing them in HTML fragments."""
    return html.escape(str(value), quote=True)


def _render_html(
    target_paper: TargetPaper,
    summary: dict[str, object],
    charts: dict[str, object],
    provenance: dict[str, object],
    citation_contexts: list[CitationContext],
) -> str:
    """Render the interactive HTML report with ECharts and no-JavaScript fallbacks."""
    def render_list(items: list[str], empty_text: str = "None") -> str:
        if not items:
            return f"<li>{empty_text}</li>"
        return "".join(f"<li>{item}</li>" for item in items)

    def render_map(items: dict[str, object], empty_text: str = "No data") -> str:
        if not items:
            return f"<li>{empty_text}</li>"
        return "".join(
            f"<li><span title=\"{key}\">{key}</span><strong>{value}</strong></li>"
            for key, value in items.items()
        )

    def render_top_scholars(items: list[dict[str, object]]) -> str:
        if not items:
            return "<p class='muted'>暂无重要学者数据。</p>"
        rows = "".join(
            (
                "<tr>"
                f"<td>{item.get('name', '')}</td>"
                f"<td>{item.get('label', '')}</td>"
                f"<td>{item.get('h_index') or 'N/A'}</td>"
                f"<td>{', '.join(list(item.get('affiliations', []))[:1]) if isinstance(item.get('affiliations'), list) else ''}</td>"
                f"<td>{', '.join(list(item.get('fields', []))[:2]) if isinstance(item.get('fields'), list) else ''}</td>"
                "</tr>"
            )
            for item in items
        )
        return f"<table class='data-table'><thead><tr><th>作者</th><th>标签</th><th>h-index</th><th>机构</th><th>领域</th></tr></thead><tbody>{rows}</tbody></table>"

    def render_representative_contexts(items: dict[str, list[dict[str, object]]]) -> str:
        sections = []
        for label in ("positive", "critical", "neutral"):
            contexts = items.get(label, [])
            if not contexts:
                continue
            cards = ""
            for context in contexts:
                paper_title = context.get("citing_paper_title") or context.get("citing_paper_id", "unknown")
                citation_index = context.get("context_index")
                summary_suffix = f" 第 {citation_index} 处" if citation_index else ""
                meta_items = []
                if context.get("citing_paper_year"):
                    meta_items.append(str(context.get("citing_paper_year")))
                if context.get("citing_paper_doi"):
                    meta_items.append(f"DOI: {context.get('citing_paper_doi')}")
                meta = f"<p class='context-meta'>{_escape_html(' | '.join(meta_items))}</p>" if meta_items else ""
                cards += (
                    "<article class='context-card compact'>"
                    f"<details class='citation-detail'>"
                    f"<summary>《{_escape_html(paper_title)}》引用了目标论文（{_display_sentiment_label(label)}）{_escape_html(summary_suffix)}</summary>"
                    f"{meta}"
                    f"<p><strong>引用内容：</strong>{_escape_html(context.get('context_text') or '暂无引用内容。')}</p>"
                    f"<p class='muted'><strong>原因：</strong>{_escape_html(context.get('reason') or _display_reason(str(context.get('evidence_note') or '')))}</p>"
                    "</details>"
                    "</article>"
                )
            sections.append(f"<h3>{_display_sentiment_label(label)}引用</h3>{cards}")
        return "".join(sections) or "<p class='muted'>暂无代表性引用语境。</p>"

    def render_author_identity_skips(items: list[dict[str, str]]) -> str:
        if not items:
            return "<p class='muted'>所有进入作者画像的施引论文均通过 work-authorship 条件。</p>"
        rows = "".join(
            (
                "<tr>"
                f"<td>{item.get('citing_paper_id', '')}</td>"
                f"<td>{item.get('title', '')}</td>"
                f"<td>{item.get('reason', '')}</td>"
                f"<td>{item.get('paper_match_confidence', '')}</td>"
                f"<td>{item.get('author_resolution_status', '')}</td>"
                "</tr>"
            )
            for item in items
        )
        return (
            "<table class='data-table'><thead><tr><th>施引论文</th><th>标题</th><th>跳过原因</th>"
            "<th>论文置信度</th><th>作者状态</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )

    def render_author_profile_breakdown(breakdown: dict[str, object]) -> str:
        rows = [
            ("重量级作者", "完整 OpenAlex author profile，h-index >= 30，且在施引论文中出现频次 >= 2。", breakdown.get("heavyweight", 0)),
            ("高影响力作者", "完整 OpenAlex author profile，h-index >= 30。", breakdown.get("high_impact", 0)),
            ("普通完整画像作者", "已查到完整 OpenAlex author profile 和 h-index，但 h-index < 30。", breakdown.get("complete_regular", 0)),
            ("完整画像缺指标作者", "已查到 OpenAlex author profile，但该 profile 缺少 h-index 等关键影响力指标。", breakdown.get("complete_missing_metric", 0)),
            ("弱画像作者", "只从可信 OpenAlex work.authorships 确认其为施引论文作者，未获得完整 author profile。", breakdown.get("weak_work_authorship", 0)),
        ]
        body = "".join(
            "<tr>"
            f"<td>{name}</td>"
            f"<td>{count}</td>"
            f"<td>{description}</td>"
            "</tr>"
            for name, description, count in rows
        )
        return (
            "<table class='data-table'><thead><tr><th>分类</th><th>数量</th><th>标准</th></tr></thead>"
            f"<tbody>{body}</tbody></table>"
        )

    chart_data = _build_html_chart_data(charts, summary, provenance)
    chart_data_json = _json_for_script(chart_data)
    world_geojson_json = _json_for_script(load_world_geojson())
    title_zh = str(summary.get("target_title_zh") or "未生成")
    arxiv_url = summary.get("target_arxiv_url")
    arxiv_html = f"<p class='meta-line'><strong>arXiv:</strong> <a href=\"{arxiv_url}\">{arxiv_url}</a></p>" if arxiv_url else ""

    contexts_html = "".join(
        (
            "<article class='context-card'>"
            f"<div class='context-head'><h3>{context.citing_paper_id}</h3><span class='sentiment-tag'>{_display_sentiment_label(context.sentiment_label)}</span></div>"
            f"<p><strong>原因：</strong> {_escape_html(_display_reason(context.evidence_note))}</p>"
            f"<p>{_escape_html(context.context_text or 'No context available.')}</p>"
            "</article>"
        )
        for context in citation_contexts
    )

    quality_summary = _build_quality_summary(summary, provenance)
    author_profile_breakdown = provenance.get("author_profile_breakdown", {})
    author_profile_breakdown = author_profile_breakdown if isinstance(author_profile_breakdown, dict) else {}
    quality_cards = "".join(
        f"<article class='quality-chip'><span>{item['label']}</span><strong>{item['value']}</strong></article>"
        for item in quality_summary["items"]
    )
    total_authors = _as_int(author_profile_breakdown.get("profile_total"))
    complete_profiles = _as_int(author_profile_breakdown.get("complete_profile_total"))
    unknown_countries = _as_int(chart_data["countryDistribution"].get("unknownCount"))
    located_countries = max(total_authors - unknown_countries, 0) if total_authors else 0
    citation_count = _as_int(summary.get("citation_count"))
    unknown_sentiments = _as_int(summary.get("unknown_sentiments"))
    classified_sentiments = max(citation_count - unknown_sentiments, 0) if citation_count else 0
    skipped_author_count = len(summary.get("author_identity_skipped_papers", [])) if isinstance(summary.get("author_identity_skipped_papers"), list) else 0
    coverage_items = [
        ("情感已分类", f"{classified_sentiments}/{citation_count}" if citation_count else "0"),
        ("国家可定位", f"{located_countries}/{total_authors}" if total_authors else "0"),
        ("完整作者画像", f"{complete_profiles}/{total_authors}" if total_authors else "0"),
        ("作者画像跳过", skipped_author_count),
    ]
    coverage_cards = "".join(
        f"<article class='quality-chip'><span>{label}</span><strong>{value}</strong></article>"
        for label, value in coverage_items
    )
    provenance_items = [
        f"部分失败: {provenance.get('partial_failure', False)}",
        f"来源追踪: {provenance.get('source_trace_count', 0)}",
    ]
    provenance_items.extend(str(note) for note in provenance.get("fetch_notes", []))
    provenance_items.extend(str(error) for error in provenance.get("state_errors", []))
    provenance_items.extend(
        f"{item.get('author_id')}: {item.get('label')}: {item.get('confidence_note')}"
        for item in provenance.get("low_confidence_labels", [])
        if isinstance(item, dict)
    )
    attention_items = list(summary.get("manual_attention_items", []))
    author_identity_skips = list(summary.get("author_identity_skipped_papers", []))

    year_fallback = _render_year_fallback(chart_data["yearTrend"])
    scholar_fallback = render_map(chart_data["scholarDistribution"]["fallback"])
    h_index_fallback = render_map(chart_data["hIndexDistribution"]["fallback"])
    sentiment_fallback = render_map(chart_data["sentimentDistribution"]["fallback"])
    country_fallback = render_map(chart_data["countryDistribution"]["fallback"])
    institution_fallback = render_map(chart_data["institutionDistribution"]["fallback"])
    attention_html = (
        "<p class='muted'>当前没有需要人工关注的项目。</p>"
        if not attention_items
        else (
            f"<details class='attention-details'><summary>查看 {len(attention_items)} 条人工关注项</summary>"
            f"<ul class='attention-list'>{render_list(attention_items)}</ul></details>"
        )
    )
    debug_appendix = f"""
    <details class="debug-block">
      <summary>作者画像分类标准</summary>
      <p class="muted">这里区分“完整作者画像”和“弱画像作者”。弱画像不代表作者不存在，而是只确认其出现在可信施引论文 authorships 中，尚未获得完整学者指标。</p>
      {render_author_profile_breakdown(author_profile_breakdown)}
    </details>
    <details class="debug-block">
      <summary>作者画像跳过说明（{len(author_identity_skips)} 条）</summary>
      <p class="muted">Stage 4 只使用可信 OpenAlex work.authorships.author.id。低置信论文、无 authorship 或无 author_id 的记录不会退回名字搜索。</p>
      {render_author_identity_skips(author_identity_skips)}
    </details>
    <details class="debug-block">
      <summary>施引作者机构分布 Top {INSTITUTION_TOP_N}</summary>
      <p class="muted">{chart_data['institutionDistribution']['note']}</p>
      <ul class="data-list">{institution_fallback}</ul>
    </details>
    <details class="debug-block">
      <summary>数据质量原始指标</summary>
      <div class="quality-grid">{quality_cards}</div>
    </details>
    <details class="debug-block">
      <summary>系统关注项与处理提示</summary>
      <ul class="attention-list">{render_list(provenance_items, 'No quality warnings')}</ul>
      {attention_html}
    </details>
    <details class="debug-block">
      <summary>全量引用上下文（{len(citation_contexts)} 条）</summary>
      <div class="context-list">{contexts_html or '<p>No contexts available.</p>'}</div>
    </details>
    <details class="debug-block">
      <summary>补充发现</summary>
      <ul class="finding-list">{render_list(list(summary.get('key_findings', [])), 'No findings generated')}</ul>
    </details>
    """

    return f"""<!doctype html>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <title>CiteAnalyzer Report - {target_paper.title or 'Unknown Target'}</title>
  <script src="{ECHARTS_CDN_URL}"></script>
  <style>
    :root {{
      --bg: #f4efe6;
      --panel: #fffaf2;
      --ink: #1f2937;
      --muted: #6b7280;
      --line: #dfd1ba;
      --accent: #9f4f2b;
      --accent-soft: #f3e0ce;
      --good: #6f8f5b;
      --warn: #b58a48;
      --risk: #b85c42;
    }}
    * {{ box-sizing: border-box; }}
    body {{ font-family: Georgia, "Times New Roman", serif; margin: 0; padding: 1.25rem; color: var(--ink); background: linear-gradient(180deg, #efe4cf 0%, var(--bg) 100%); }}
    section {{ margin-bottom: 1rem; }}
    h1, h2, h3, p {{ margin-top: 0; }}
    h1 {{ font-size: clamp(1.65rem, 2.6vw, 2.6rem); line-height: 1.08; letter-spacing: -0.035em; margin-bottom: 0.75rem; max-width: 980px; }}
    h2 {{ margin-bottom: 0.55rem; }}
    .report-page {{ max-width: 1500px; margin: 0 auto; }}
    .top-grid {{ display: grid; grid-template-columns: minmax(0, 760px) minmax(620px, 1fr); gap: 1rem; align-items: start; margin-bottom: 1rem; }}
    .top-left {{ display: flex; flex-direction: column; gap: 0.8rem; min-width: 0; }}
    .top-right {{ min-width: 0; }}
    .top-summary {{ min-height: 100%; }}
    .report-grid {{ display: grid; grid-template-columns: minmax(0, 760px) minmax(620px, 1fr); gap: 1rem; align-items: start; justify-content: space-between; }}
    .primary-column, .secondary-column {{ min-width: 0; }}
    .primary-column {{ max-width: 760px; width: 100%; }}
    .secondary-column {{ position: sticky; top: 1rem; }}
    .hero {{ border: 1px solid var(--line); border-radius: 20px; padding: 1.15rem 1.25rem; background: radial-gradient(circle at top left, #fff7eb 0%, var(--panel) 60%); box-shadow: 0 12px 30px rgba(95, 63, 38, 0.08); }}
    .hero p {{ color: var(--muted); margin-bottom: 0.35rem; }}
    .subtitle-zh {{ color: var(--accent); font-size: 1.08rem; margin-top: -0.25rem; margin-bottom: 0.65rem; }}
    .meta-line {{ margin-top: 0.25rem; overflow-wrap: anywhere; }}
    .meta-line a {{ color: var(--accent); }}
    .page-nav {{ display: flex; flex-wrap: wrap; gap: 0.45rem; margin: 0; border: 1px solid var(--line); border-radius: 18px; padding: 0.7rem; background: rgba(255, 250, 242, 0.88); }}
    .page-nav a {{ color: var(--accent); text-decoration: none; padding: 0.45rem 0.7rem; border: 1px solid var(--line); border-radius: 999px; background: rgba(255, 255, 255, 0.68); font-size: 0.92rem; }}
    .chart-grid {{ display: grid; grid-template-columns: repeat(2, minmax(250px, 1fr)); gap: 0.8rem; }}
    .side-chart-grid {{ display: grid; grid-template-columns: repeat(2, minmax(260px, 1fr)); gap: 0.55rem; margin-bottom: 0; }}
    .card {{ border: 1px solid var(--line); border-radius: 16px; padding: 0.9rem; background: rgba(255, 250, 242, 0.96); }}
    .muted {{ color: var(--muted); }}
    .quality-panel {{ border: 1px solid var(--line); border-radius: 18px; padding: 0.95rem; background: rgba(255, 250, 242, 0.94); }}
    .quality-head {{ display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 0.75rem; }}
    .quality-badge {{ display: inline-flex; align-items: center; border-radius: 999px; padding: 0.35rem 0.75rem; color: #fffaf2; background: var(--good); font-weight: 700; }}
    .quality-badge[data-level="warning"] {{ background: var(--warn); }}
    .quality-badge[data-level="risk"] {{ background: var(--risk); }}
    .quality-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 0.55rem; margin-top: 0.75rem; }}
    .quality-chip {{ border: 1px solid var(--line); border-radius: 14px; padding: 0.65rem; background: rgba(255, 255, 255, 0.55); }}
    .quality-chip span {{ display: block; color: var(--muted); font-size: 0.9rem; }}
    .quality-chip strong {{ color: var(--accent); font-size: 1.25rem; }}
    .chart-card {{ min-height: 320px; }}
    .chart-card.wide {{ grid-column: 1 / -1; }}
    .side-chart-grid .chart-card {{ min-height: 225px; padding: 0.65rem; }}
    .side-chart-grid .chart-card h2 {{ font-size: 1.02rem; line-height: 1.2; }}
    .chart-card h2 {{ margin-bottom: 0.35rem; }}
    .chart-note {{ color: var(--muted); font-size: 0.9rem; min-height: 2.1rem; }}
    .side-chart-grid .chart-note {{ font-size: 0.78rem; line-height: 1.28; min-height: 0; margin-bottom: 0.25rem; }}
    .chart-panel {{ height: 230px; min-height: 230px; margin-top: 0.45rem; }}
    .chart-card.wide .chart-panel {{ height: 330px; }}
    .side-chart-grid .chart-panel {{ height: 140px; min-height: 140px; margin-top: 0.25rem; }}
    .chart-card[data-chart-state="fallback"] .chart-panel {{ display: none; }}
    .chart-card[data-chart-state="chart"] .chart-fallback {{ display: none; }}
    .chart-fallback {{ margin-top: 0.75rem; }}
    .list-card ul, .attention-list, .finding-list, .data-list {{ padding-left: 1.2rem; margin: 0; }}
    .top-summary .finding-list {{ font-size: 1.04rem; line-height: 1.62; }}
    .top-summary .finding-list li {{ margin-bottom: 0.45rem; }}
    .report-coverage {{ margin-top: 1rem; margin-bottom: 1rem; }}
    .report-coverage .quality-head {{ align-items: flex-start; }}
    .report-coverage h2 {{ margin-bottom: 0.35rem; }}
    .report-coverage .quality-grid {{ grid-template-columns: repeat(4, minmax(140px, 1fr)); }}
    .data-list li {{ display: flex; justify-content: space-between; gap: 1rem; padding: 0.2rem 0; }}
    .data-list span {{ color: var(--muted); overflow-wrap: anywhere; }}
    .attention-list li {{ color: var(--accent); }}
    .attention-details summary {{ cursor: pointer; color: var(--accent); font-weight: 700; margin-bottom: 0.75rem; }}
    .debug-appendix {{ border-style: dashed; background: rgba(255, 250, 242, 0.82); }}
    .debug-block {{ border-top: 1px solid var(--line); padding: 0.85rem 0; }}
    .debug-block:first-of-type {{ border-top: 0; padding-top: 0; }}
    .debug-block summary {{ cursor: pointer; color: var(--accent); font-weight: 700; line-height: 1.45; }}
    .debug-block[open] summary {{ margin-bottom: 0.75rem; }}
    .data-table {{ width: 100%; border-collapse: collapse; overflow: hidden; border-radius: 14px; background: rgba(255, 250, 242, 0.96); }}
    .data-table th, .data-table td {{ border: 1px solid var(--line); padding: 0.55rem; text-align: left; vertical-align: top; font-size: 0.92rem; }}
    .data-table th {{ background: var(--accent-soft); color: var(--accent); }}
    .context-list {{ border: 1px solid var(--line); border-radius: 18px; padding: 0.95rem; background: rgba(255, 250, 242, 0.92); }}
    .context-card {{ border-top: 1px solid var(--line); padding-top: 0.8rem; margin-top: 0.8rem; }}
    .context-card:first-child {{ border-top: 0; margin-top: 0; padding-top: 0; }}
    .context-card.compact {{ border: 1px solid var(--line); border-radius: 14px; padding: 0.9rem; background: rgba(255, 250, 242, 0.72); }}
    .context-head {{ display: flex; justify-content: space-between; align-items: baseline; gap: 1rem; }}
    .citation-detail summary {{ cursor: pointer; color: var(--ink); font-weight: 700; line-height: 1.45; }}
    .citation-detail p {{ margin: 0.7rem 0 0; }}
    .context-meta {{ color: var(--muted); font-size: 0.92rem; }}
    .sentiment-tag {{ color: var(--accent); font-weight: 700; text-transform: capitalize; }}
    @media (max-width: 1240px) {{
      .top-grid, .report-grid {{ grid-template-columns: 1fr; }}
      .primary-column {{ max-width: none; }}
      .secondary-column {{ position: static; }}
      .chart-grid {{ grid-template-columns: repeat(2, minmax(260px, 1fr)); }}
      .side-chart-grid {{ grid-template-columns: repeat(2, minmax(260px, 1fr)); }}
    }}
    @media (max-width: 720px) {{
      body {{ padding: 1rem; }}
      h1 {{ font-size: 1.7rem; }}
      .chart-grid, .side-chart-grid {{ grid-template-columns: 1fr; }}
      .chart-card.wide {{ grid-column: auto; }}
      .chart-panel {{ height: 240px; }}
      .chart-card.wide .chart-panel {{ height: 260px; }}
      .page-nav {{ gap: 0.45rem; }}
    }}
  </style>
</head>
<body>
  <main class="report-page">
  <section class="top-grid">
    <div class="top-left">
      <section class="hero" id="overview">
        <h1>{target_paper.title or 'Unknown Target Paper'}</h1>
        <p class="subtitle-zh"><strong>中文标题:</strong> {title_zh}</p>
        <p><strong>DOI:</strong> {target_paper.doi or 'N/A'}</p>
        {arxiv_html}
      </section>
      <nav class="page-nav">
        <a href="#overview">概览</a>
        <a href="#summary">分析摘要</a>
        <a href="#charts">可视化图表</a>
        <a href="#scholars">重要学者</a>
        <a href="#representative-contexts">代表性引用</a>
        <a href="#quality">数据覆盖</a>
        <a href="#debug-appendix">调试附录</a>
      </nav>
      <section id="summary" class="card list-card top-summary">
        <h2>分析摘要</h2>
        <ul class="finding-list">{render_list(list(summary.get('executive_summary', [])), '暂无分析摘要')}</ul>
      </section>
    </div>
    <div class="top-right">
      <section class="side-chart-grid" id="charts">
        <article class="card chart-card" data-chart-state="{chart_data['yearTrend']['state']}">
          <h2>引用年份趋势</h2>
          <p class="chart-note">{chart_data['yearTrend']['note']}</p>
          <div class="chart-panel" id="yearTrendChart" role="img" aria-label="引用年份趋势图"></div>
          <div class="chart-fallback">{year_fallback}</div>
        </article>
        <article class="card chart-card" data-chart-state="{chart_data['sentimentDistribution']['state']}">
          <h2>引用情感分布</h2>
          <p class="chart-note">{chart_data['sentimentDistribution']['note']}</p>
          <div class="chart-panel" id="sentimentDistributionChart" role="img" aria-label="引用情感分布图"></div>
          <ul class="data-list chart-fallback">{sentiment_fallback}</ul>
        </article>
        <article class="card chart-card" data-chart-state="{chart_data['hIndexDistribution']['state']}">
          <h2>作者 h-index 分布</h2>
          <p class="chart-note">{chart_data['hIndexDistribution']['note']}</p>
          <div class="chart-panel" id="hIndexDistributionChart" role="img" aria-label="作者 h-index 分布图"></div>
          <ul class="data-list chart-fallback">{h_index_fallback}</ul>
        </article>
        <article class="card chart-card" data-chart-state="{chart_data['scholarDistribution']['state']}">
          <h2>学者质量分布</h2>
          <p class="chart-note">{chart_data['scholarDistribution']['note']}</p>
          <div class="chart-panel" id="scholarDistributionChart" role="img" aria-label="学者质量分布图"></div>
          <ul class="data-list chart-fallback">{scholar_fallback}</ul>
        </article>
      </section>
    </div>
  </section>
  <section class="report-grid">
    <div class="primary-column">
      <article class="card chart-card wide" data-chart-state="{chart_data['countryDistribution']['state']}">
        <h2>施引来源国家/地区地图</h2>
        <p class="chart-note">{chart_data['countryDistribution']['note']}</p>
        <div class="chart-panel" id="countryDistributionChart" role="img" aria-label="施引来源国家地区分布图"></div>
        <ul class="data-list chart-fallback">{country_fallback}</ul>
      </article>
      <section id="representative-contexts" class="context-list">
        <h2>代表性引用语境</h2>
        {render_representative_contexts(summary.get('representative_contexts', {}))}
      </section>
    </div>
    <aside class="secondary-column">
      <section id="scholars" class="card">
        <h2>重要学者</h2>
        {render_top_scholars(list(summary.get('top_scholars', [])))}
      </section>
    </aside>
  </section>
  <section id="quality" class="card quality-panel report-coverage">
    <div class="quality-head">
      <div>
        <h2>数据覆盖情况</h2>
        <p class="muted">{quality_summary['note']}</p>
      </div>
      <span class="quality-badge" data-level="{quality_summary['level']}">{quality_summary['label']}</span>
    </div>
    <div class="quality-grid">{coverage_cards}</div>
  </section>
  <section id="debug-appendix" class="card debug-appendix">
    <h2>调试附录</h2>
    <p class="muted">这里保留工程排查和数据复核所需的明细，默认折叠，避免干扰报告主线阅读。</p>
    {debug_appendix}
  </section>
  </main>
  <script type="application/json" id="chart-data">{chart_data_json}</script>
  <script type="application/json" id="world-geojson">{world_geojson_json}</script>
  <script>
    (() => {{
      const source = document.getElementById("chart-data");
      if (!source || !window.echarts) return;
      const payload = JSON.parse(source.textContent);
      const worldGeoJsonSource = document.getElementById("world-geojson");
      const worldGeoJson = worldGeoJsonSource ? JSON.parse(worldGeoJsonSource.textContent) : null;
      if (worldGeoJson) {{
        echarts.registerMap("world", worldGeoJson);
      }}
      const initChart = (id, state, option) => {{
        if (state !== "chart") return;
        const element = document.getElementById(id);
        if (!element) return;
        const chart = echarts.init(element, null, {{ renderer: "svg" }});
        chart.setOption(option);
        window.addEventListener("resize", () => chart.resize());
      }};
      const axisLabel = {{ color: "#6b7280" }};
      const splitLine = {{ lineStyle: {{ color: "rgba(159, 79, 43, 0.14)" }} }};

      initChart("yearTrendChart", payload.yearTrend.state, {{
        color: ["#9f4f2b"],
        tooltip: {{ trigger: "axis" }},
        grid: {{ left: 44, right: 18, top: 24, bottom: 34 }},
        xAxis: {{ type: "category", data: payload.yearTrend.labels, axisLabel }},
        yAxis: {{ type: "value", minInterval: 1, axisLabel, splitLine }},
        series: [{{ type: "bar", data: payload.yearTrend.values, barMaxWidth: 34, label: {{ show: true, position: "top" }}, itemStyle: {{ borderRadius: [8, 8, 0, 0] }} }}]
      }});

      initChart("hIndexDistributionChart", payload.hIndexDistribution.state, {{
        color: ["#9f4f2b"],
        tooltip: {{ trigger: "axis", axisPointer: {{ type: "shadow" }} }},
        grid: {{ left: 48, right: 18, top: 22, bottom: 34 }},
        xAxis: {{ type: "category", data: payload.hIndexDistribution.labels, axisLabel }},
        yAxis: {{ type: "value", minInterval: 1, axisLabel, splitLine }},
        series: [{{ type: "bar", data: payload.hIndexDistribution.values, barMaxWidth: 28, label: {{ show: true, position: "top" }}, itemStyle: {{ borderRadius: [8, 8, 0, 0] }} }}]
      }});

      initChart("scholarDistributionChart", payload.scholarDistribution.state, {{
        color: ["#b58a48"],
        tooltip: {{ trigger: "axis", axisPointer: {{ type: "shadow" }} }},
        grid: {{ left: 108, right: 24, top: 22, bottom: 28 }},
        xAxis: {{ type: "value", minInterval: 1, axisLabel, splitLine }},
        yAxis: {{ type: "category", data: payload.scholarDistribution.labels, axisLabel }},
        series: [{{ type: "bar", data: payload.scholarDistribution.values, barMaxWidth: 24, label: {{ show: true, position: "right" }}, itemStyle: {{ borderRadius: [0, 8, 8, 0] }} }}]
      }});

      initChart("sentimentDistributionChart", payload.sentimentDistribution.state, {{
        tooltip: {{ trigger: "item" }},
        legend: {{ bottom: 0, textStyle: axisLabel }},
        series: [{{
          type: "pie",
          radius: ["38%", "68%"],
          center: ["50%", "45%"],
          data: payload.sentimentDistribution.items,
          label: {{ formatter: "{{b}}: {{c}}" }},
          itemStyle: {{ color: item => item.data.color }}
        }}]
      }});

      initChart("countryDistributionChart", payload.countryDistribution.state, {{
        tooltip: {{
          trigger: "item",
          formatter: params => `${{params.name}}: ${{params.value || 0}}`
        }},
        visualMap: {{
          min: 0,
          max: payload.countryDistribution.maxValue || 1,
          left: 12,
          bottom: 16,
          text: ["高", "低"],
          calculable: true,
          inRange: {{ color: ["#f7e8d1", "#c98a4a", "#7f3418"] }}
        }},
        series: [{{
          name: "施引来源",
          type: "map",
          map: "world",
          roam: true,
          emphasis: {{ label: {{ show: true }} }},
          data: payload.countryDistribution.mapItems
        }}]
      }});

    }})();
  </script>
</body>
</html>
"""


def _build_html_chart_data(
    charts: dict[str, object],
    summary: dict[str, object],
    provenance: dict[str, object],
) -> dict[str, object]:
    """Convert chart payloads into HTML-ready series data and fallback states."""
    year_trend = _coerce_int_map(charts.get("year_trend"))
    scholar_distribution = _coerce_int_map(charts.get("scholar_distribution"))
    sentiment_distribution = _coerce_int_map(charts.get("sentiment_distribution"))
    country_distribution = _coerce_int_map(charts.get("country_distribution"))
    institution_distribution = _coerce_int_map(charts.get("institution_distribution")) or _coerce_int_map(charts.get("source_map"))
    h_index_distribution = _coerce_int_map(charts.get("h_index_distribution"))

    year_labels = list(year_trend.keys())
    year_values = list(year_trend.values())
    year_state = "chart" if len(year_labels) >= 1 else "fallback"

    author_profile_breakdown = provenance.get("author_profile_breakdown")
    author_profile_breakdown = author_profile_breakdown if isinstance(author_profile_breakdown, dict) else {}
    regular_scholar_count = _as_int(author_profile_breakdown.get("complete_regular")) + _as_int(author_profile_breakdown.get("complete_missing_metric")) + _as_int(author_profile_breakdown.get("weak_work_authorship"))
    scholar_items = [
        ("重量级", scholar_distribution.get("heavyweight_candidate", 0)),
        ("高影响力", scholar_distribution.get("high_impact_candidate", 0)),
        ("普通学者", regular_scholar_count or scholar_distribution.get("weak_signal_candidate", 0)),
    ]
    scholar_items = [(label, count) for label, count in scholar_items if count > 0]
    scholar_state = "chart" if len(scholar_items) >= 1 else "fallback"
    h_index_items = [(label, count) for label, count in h_index_distribution.items() if count > 0]
    h_index_state = "chart" if h_index_items else "fallback"

    sentiment_items = [
        (
            _display_sentiment_label(label),
            sentiment_distribution.get(label, 0),
            SENTIMENT_COLORS.get(label, "#9f4f2b"),
        )
        for label in SENTIMENT_ORDER
        if sentiment_distribution.get(label, 0) > 0
    ]
    sentiment_state = "chart" if len(sentiment_items) >= 1 else "fallback"

    country_items = _top_n_with_others(country_distribution, limit=INSTITUTION_TOP_N)
    country_map_payload = build_country_map_payload(country_distribution)
    country_state = "chart" if country_map_payload["items"] else "fallback"
    institution_items = _top_n_with_others(institution_distribution, limit=INSTITUTION_TOP_N)
    institution_state = "chart" if len(institution_items) >= 1 else "fallback"

    return {
        "yearTrend": {
            "state": year_state,
            "note": _year_trend_note(year_trend, summary),
            "labels": year_labels,
            "values": year_values,
            "fallback": year_trend,
        },
        "scholarDistribution": {
            "state": scholar_state,
            "note": "基于可信 work-authorship 作者画像统计。重量级：h-index ≥ 30 且在施引集合出现 ≥ 2 次；高影响力：h-index ≥ 30；普通学者：其余已识别作者。",
            "labels": [label for label, _ in scholar_items],
            "values": [count for _, count in scholar_items],
            "fallback": dict(scholar_items) or {"暂无学者标签": 0},
        },
        "hIndexDistribution": {
            "state": h_index_state,
            "note": "按 OpenAlex author profile 的 h-index 分桶统计；没有 h-index 的作者不计入此图。",
            "labels": list(h_index_distribution.keys()),
            "values": list(h_index_distribution.values()),
            "fallback": h_index_distribution or {"暂无 h-index 数据": 0},
        },
        "sentimentDistribution": {
            "state": sentiment_state,
            "note": "未知表示证据不足，不应被当作普通情绪类别。",
            "labels": [label for label, _, _ in sentiment_items],
            "values": [count for _, count, _ in sentiment_items],
            "items": [
                {"value": count, "name": label, "color": color}
                for label, count, color in sentiment_items
            ],
            "fallback": {
                _display_sentiment_label(label): count
                for label, count in sentiment_distribution.items()
                if count > 0
            }
            or {"暂无情感分类": 0},
        },
        "countryDistribution": {
            "state": country_state,
            "note": _country_map_note(country_map_payload),
            "labels": [label for label, _ in country_items],
            "values": [count for _, count in country_items],
            "mapItems": country_map_payload["items"],
            "unknownCount": country_map_payload["unknownCount"],
            "unmappedItems": country_map_payload["unmappedItems"],
            "maxValue": country_map_payload["maxValue"],
            "fallback": dict(country_items) or {"暂无国家/地区信息": 0},
            "raw_count": len(country_distribution),
        },
        "institutionDistribution": {
            "state": institution_state,
            "note": "按作者首条机构文本聚合；这不是世界地图。",
            "labels": [label for label, _ in reversed(institution_items)],
            "values": [count for _, count in reversed(institution_items)],
            "fallback": dict(institution_items) or {"暂无机构信息": 0},
            "raw_count": len(institution_distribution),
        },
        "quality": _build_quality_summary(summary, provenance),
    }


def _build_quality_summary(summary: dict[str, object], provenance: dict[str, object]) -> dict[str, object]:
    """Summarize upstream failures and coverage gaps into a data-quality badge."""
    unknown = _as_int(summary.get("unknown_sentiments"))
    partial_failure = bool(summary.get("partial_failure"))
    fetch_notes = provenance.get("fetch_notes") if isinstance(provenance.get("fetch_notes"), list) else []
    state_errors = provenance.get("state_errors") if isinstance(provenance.get("state_errors"), list) else []
    low_confidence = provenance.get("low_confidence_labels")
    low_confidence_count = len(low_confidence) if isinstance(low_confidence, list) else 0
    skipped_author_identity = provenance.get("author_identity_skipped_papers")
    skipped_author_identity_count = len(skipped_author_identity) if isinstance(skipped_author_identity, list) else 0
    breakdown = provenance.get("author_profile_breakdown")
    breakdown = breakdown if isinstance(breakdown, dict) else {}
    weak_work_authorship = _as_int(breakdown.get("weak_work_authorship"))
    complete_profile_total = _as_int(breakdown.get("complete_profile_total"))
    complete_regular = _as_int(breakdown.get("complete_regular"))
    complete_missing_metric = _as_int(breakdown.get("complete_missing_metric"))

    if partial_failure or state_errors:
        level = "risk"
        label = "需复核"
        note = "存在上游部分失败或状态错误，结论需要结合详情复核。"
    elif unknown > 0 or fetch_notes or skipped_author_identity_count:
        level = "warning"
        label = "部分缺失"
        note = "存在未知情感、抓取提示或作者画像跳过记录，部分证据不足。"
    else:
        level = "ok"
        label = "可靠"
        note = "未发现阻塞性失败，报告可作为当前数据快照阅读。"

    return {
        "level": level,
        "label": label,
        "note": note,
        "items": [
            {"label": "未知情感", "value": unknown},
            {"label": "抓取提示", "value": len(fetch_notes)},
            {"label": "状态错误", "value": len(state_errors)},
            {"label": "完整画像作者", "value": complete_profile_total},
            {"label": "普通完整画像", "value": complete_regular},
            {"label": "完整画像缺指标", "value": complete_missing_metric},
            {"label": "弱画像作者", "value": weak_work_authorship},
            {"label": "作者跳过", "value": skipped_author_identity_count},
        ],
    }


def _render_year_fallback(year_trend: dict[str, object]) -> str:
    """Describe year data when a trend chart would be visually misleading."""
    fallback = year_trend.get("fallback")
    if not isinstance(fallback, dict) or not fallback:
        return "<p class='muted chart-fallback'>暂无年份数据。</p>"
    return "<ul class='data-list chart-fallback'>" + "".join(
        f"<li><span>{year}</span><strong>{count}</strong></li>"
        for year, count in fallback.items()
    ) + "</ul>"


def _year_trend_note(year_trend: dict[str, int], summary: dict[str, object]) -> str:
    """Explain whether the year chart represents a trend or a small-sample count."""
    if len(year_trend) >= 2:
        return "展示施引文献按年份分布，用于判断影响是否持续扩散。"
    if len(year_trend) == 1:
        year, count = next(iter(year_trend.items()))
        return f"当前样本集中在 {year} 年，共 {count} 篇施引文献。"
    return f"当前 {summary.get('citation_count', 0)} 篇施引文献缺少年份信息。"


def _country_map_note(country_map_payload: dict[str, object]) -> str:
    """Explain map coverage, including Unknown and unmapped country buckets."""
    unknown_count = _as_int(country_map_payload.get("unknownCount"))
    unmapped_items = country_map_payload.get("unmappedItems")
    unmapped_count = 0
    if isinstance(unmapped_items, list):
        unmapped_count = sum(_as_int(item.get("value")) for item in unmapped_items if isinstance(item, dict))
    notes = ["优先使用 OpenAlex 明确国家代码/国家名；缺少明确国家时，再由 LLM 根据作者名、OpenAlex ID 与机构信息判断国家/地区。"]
    if unknown_count:
        notes.append(f"Unknown={unknown_count} 不参与地图着色。")
    if unmapped_count:
        notes.append(f"未映射地区共 {unmapped_count} 条，保留在下方列表中。")
    return " ".join(notes)


def _coerce_int_map(value: object) -> dict[str, int]:
    """Normalize chart count mappings into string labels and integer counts."""
    if not isinstance(value, dict):
        return {}
    result = {}
    for key, raw_count in value.items():
        count = _as_int(raw_count)
        if count < 0:
            continue
        result[str(key)] = count
    return result


def _nonzero_items(items: dict[str, int]) -> list[tuple[str, int]]:
    return [
        (label, count)
        for label, count in sorted(items.items(), key=lambda item: (-item[1], item[0]))
        if count > 0
    ]


def _top_n_with_others(items: dict[str, int], limit: int) -> list[tuple[str, int]]:
    """Keep top chart categories and fold the rest into an Others bucket."""
    nonzero = _nonzero_items(items)
    if len(nonzero) <= limit:
        return nonzero
    top_items = nonzero[:limit]
    other_count = sum(count for _, count in nonzero[limit:])
    if other_count:
        top_items.append(("Others", other_count))
    return top_items


def _as_int(value: object) -> int:
    """Convert optional report metric values into safe integers."""
    try:
        return int(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return 0


def _json_for_script(value: object) -> str:
    return json.dumps(value, ensure_ascii=False).replace("</", "<\\/")


def _slugify(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-") or "report"
